### ISSUE TITLE
npip.js syntax error

### ISSUE THREAD

**Issue by puresec-dor** [puresec/serverless-puresec-cli#4]
`> serverless-puresec-cli@1.0.1 install /home/dor/workspace/aws-node-rest-api-with-dynamodb/node_modules/serverless-puresec-cli
> npip install

/home/dor/workspace/aws-node-rest-api-with-dynamodb/node_modules/nopy/src/npip.js:6
const { findPackage, spawnPython } = require("./api");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
npm WARN aws-rest-with-dynamodb@1.0.0 No repository field.
npm ERR! Linux 4.10.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save-dev" "serverless-puresec-cli"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! serverless-puresec-cli@1.0.1 install: `npip install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-puresec-cli@1.0.1 install script 'npip install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless-puresec-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npip install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless-puresec-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless-puresec-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dor/workspace/aws-node-rest-api-with-dynamodb/npm-debug.log
`

**Comment by odedniv** [comment]
Can you try updating `node`?

**Comment by avi-puresec** [comment]
Fixed with updating node.
